<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-K932JURE" name="Student login" tests="2" failures="1" timestamp="14 Sep 2021 08:25:15 GMT" time="75.383" errors="0">
  <testcase name="userLogin" time="14.405" classname="studentTests.StudentLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Qualicoach] but found [Qualicoach: Log in to the site]">
      <![CDATA[java.lang.AssertionError: expected [Qualicoach] but found [Qualicoach: Log in to the site]
	at studentTests.StudentLoginTest.userLogin(StudentLoginTest.java:31)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- userLogin -->
  <testcase name="userLogin" time="52.289" classname="studentTests.StudentLoginTest"/>
</testsuite> <!-- Student login -->
